on:
  pull_request:
    types: [opened, synchronize, reopened]

# cancel previous runs on the same PR
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: ⛷ PR tests

env:
  CI: true
  NODE_VERSION: 16
  HUSKY: 0

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        package: ['backend', 'frontend', 'interfaces']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/bifrost-starter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@7.12.2 --activate
      - name: Install dependencies
        run: pnpm install
      - name: eslint
        run: pnpm run --if-present --filter ${{ matrix.package }} lint
      - name: Stylelint
        run: pnpm run --if-present --filter ${{ matrix.package }} lint:style
      - name: Tests
        run: pnpm run --if-present --filter ${{ matrix.package }} test:coverage
      - name: dependency cruiser
        run: pnpm run --if-present --filter ${{ matrix.package }} test:circular
  security-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/bifrost-starter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@7.12.2 --activate
      - name: Install dependencies
        run: pnpm install
      - name: Check for vulnerable dependencies
        run: pnpm run security
